import UIKit

struct StringConstants {
    static let k_Lbl_continue: String = "Continue"
    static let k_: String = ""
    static let k_Msg_login_with_goog: String = "Login with Google"
    static let k_Lbl_email: String = "Email"
    static let k_Lbl_your_email: String = "Your Email"
    static let k_Lbl_next: String = "Next"
    static let k_Lbl_easy_to_use: String = "Easy to Use"
    static let k_Msg_don_t_have_an_a: String = "Don’t have an account? Sign Up"
    static let k_Msg_don_t_have_an_a4: String = "Don’t have an account?"
    static let k_Msg_don_t_have_an_a3: String = "Don’t have an account? Register"
    static let k_Msg_don_t_have_an_a2: String = "Don’t have an account?"
    static let k_Lbl_previous: String = "Previous"
    static let k_Msg_bootstrap_based: String = "Bootstrap based code for everyone"
    static let k_Lbl_app_navigation: String = "App Navigation"
    static let k_Msg_welcome_let_s: String = "Welcome, let’s get started"
    static let k_Lbl_log_in: String = "Log In"
    static let k_Lbl_lorem_ipsum: String = "Lorem Ipsum"
    static let k_Msg_sign_in_to_cont: String = "Sign in to continue"
    static let k_Lbl_welcome: String = "Welcome"
    static let k_Lbl_onboarding_ccc: String = "Onboarding CCC"
    static let k_Http_Fail: String = "HTTP request failed"
    static let k_Lbl_sign_in: String = "Sign In"
    static let k_Msg_login_with_face: String = "Login with Facebook"
    static let k_Unable_To_Fetch: String = "Unable to fetch data"
    static let k_Msg_check_your_app: String = "Check your app's UI from the below demo screens of your app."
    static let k_Lbl_sign_up: String = "Sign Up"
    static let k_Msg_lorem_ipsum_is: String = "Lorem ipsum is a dummy text in advertising since lorem ipsum years"
    static let k_Lbl_password: String = "Password"
    static let k_Msg_lorem_ipsum_dol: String = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    static let k_Lbl_or: String = "OR"
    static let k_Msg_forgot_password: String = "Forgot Password?"
    static let k_Lbl_register: String = "Register"
    static let k_Invalid_URL: String = "Invalid URL"
    static let k_Lbl_login_1: String = "Login 1"
    static let k_Lbl_login_2: String = "Login 2"
}
